version: '3.8'

services:
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - TEST_DATABASE_URL=postgresql+asyncpg://test_user:test_password@test_db:5432/test_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USE_ASYNC=${USE_ASYNC:-True}
    depends_on:
      - db
      - test_db

  db:
    image: ankane/pgvector:latest
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: ankane/pgvector:latest
    container_name: test_db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5434:5432"

volumes:
  pgdata:
